---
- hosts: db
  vars_files:
    - secret.yml
  tasks:
    - name: include vars
      include_vars: secret.yml

    - name: copy MariaDB repo to yum repo
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Download the MariaDB client 
      become: yes
      package: name=MariaDB-client update_cache=yes state=present

    - name: Unzip the database files
      become: true
      unarchive: src=db/db.tgz dest=~/ mode=0777

    - name: Run the script to make the database
      become: yes
      command: ./make_databases.sh {{ db_password }} tf-201611240157431477804885jd.cwssjdtggppd.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True
