---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: tf-201612030151143063358634pu.cwssjdtggppd.us-west-2.rds.amazonaws.com
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: Include Secret
      include_vars: secret.yml

    - name: Yum epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Install PHP 5.4
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo

    - name: Download and install nginx
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install
    
    - name: Download composer
      become: yes
      get_url:
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer
        mode: 0700

    - name: Install composer
      become: yes
      shell: php /usr/local/bin/composer --install-dir=/usr/local/bin --filename=composer

    - name: Configure nginx
      become: yes
      copy: src=~/cit-360/ansible/web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf

    - name: Configure vhost
      become: yes
      template: src=~/cit-360/ansible/web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: Configure php
      become: yes
      template: src=~/cit-360/ansible/web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: Configure php-fpm-web
      become: yes
      copy: src=~/cit-360/ansible/web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: Restart nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: Restart php-fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: Directory
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: Unpack 
      become: yes
      unarchive: src=~/cit-360/ansible/web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: Composer
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}
      ignore_errors: True     

    - name: Permissions
      become: yes
      file: recurse=yes path={{ service_dir }}/storage mode=0777

    - name: Permission nginx
      become: yes
      file: recurse=yes path={{ service_dir }} owner=nginx group=nginx

    - name: Template
      become: yes
      template: src=~/cit-360/ansible/web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx
