---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: tf-201611240157431477804885jd.cwssjdtggppd.us-west-2.rds.amazonaws.com
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  vars_files:
    - secret.yml
  tasks:
    - name: Include Secrets
      include_vars: secret.yml

    - name: Change SELinux to permissive
      become: yes
      lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=" line="SELINUX=permissive"

    - name: 1
      become: yes
      command: setenforce 0

    - name: Install epel
      become: yes
      package: name=epel-release update_cache=yes state=present

    - name: Install php and dependencies
      become: yes
      shell: yes | yum install php php-gd php-mysql php-mcrypt php-fpm php-ldap php-mbstring php-phpunit-PHPUnit

    - name: Install nginx
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install

    - name: Download composer
      become: yes
      get_url:
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer
        mode: 0777
     
    - name: Install composer
      become: yes
      shell: php /usr/local/bin/composer --install-dir=/usr/local/bin --filename=composer

    - name: Copy nginx to nginx dir
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0777
      register: nginx_conf

    - name: Configure vhost.conf
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0777
      register: vhost_conf

    - name: Configure php
      become: yes
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0777
      register: php_conf

    - name: copy php-fpm-web conf 
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0777
      register: php_fpm_conf

    - name: Restart nginx if changes are made
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: Restart php if changes are made
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: Create directory
      become: yes
      file: path={{ service_dir }}/ state=directory

    - name: Unzip service conf
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest={{ service_dir }} mode=0755

    - name: Update nginx files with composer
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

    - name: Make directory
      become: yes
      file: path={{ service_dir }}/storage mode=0777 recurse=yes

    - name: Change the owner of the nginx directory
      become: yes
      file: path={{ service_dir }} owner=nginx group=nginx recurse=yes

    - name: set up web environment
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx

